### ISSUE TITLE
The title screen looks like frick on large screens

### ISSUE THREAD

**Issue by Benjamemes** [potatoco-games/Meme-game-project#1]
So, here's a problem, I'm currently on a 5K iMac and the title screen looks like this: 
<img width="418" alt="screen shot 2017-07-29 at 10 03 46" src="https://user-images.githubusercontent.com/30363847/28743596-4019b260-7445-11e7-9b20-78bb8c54dfbf.png">
So yeah, that's not good. 👎

**Comment by tobster1912** [comment]
I'll sort it out, it may have something to do with the canvas scaler, which may be the problem.

**Comment by Benjamemes** [comment]
Nice, thanks!

**Comment by tobster1912** [comment]
No problem! :)

**Comment by tobster1912** [comment]
Hey, what is your custom game screen resolution (1366x768). That's the max for windows, which is what I use, what's yours?

**Comment by Benjamemes** [comment]
5120 x 2880

**Comment by tobster1912** [comment]
Ok, I'll add it and help you out!

**Comment by Benjamemes** [comment]
Okay, @tobster1912 Fixed it, for some reason he can't close an issue
